### ISSUE TITLE
Converting OSM file to GeoJSON

### ISSUE THREAD

**Issue by pratikyadav** [batpad/geojson-flatten-tags#1]
@batpad  this is great stuff. I usually map things in JOSM and later want to use them as GeoJSON. Previously I was using http://tyrasd.github.io/osmtogeojson/ but it doesn't preserve the tags. Can we have an option here to directly convert OSM file into flattened tag GeoJSON?

Also would be great if we could browse file rather than pasting text(just an idea).

**Comment by batpad** [comment]
@pratikyadav it now accepts the XML directly as well as allows you to pick a file from your computer. Closing.
